name: bundlecleaner-env
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- jupyter=1.0.0
- scikit-learn
- scipy
- seaborn
- matplotlib
- nomkl
- plotly
- tqdm
- dipy
- fury
- openpyxl
- pip
- pip:
  - dipy==1.7.0
  - fury==0.9.0
  - robust_laplacian
  - kneed